# dev — Harbor image, ns platform-demo-dev.
minicloud-app-deployment:
  image:
    repository: harbor.10.0.0.200.nip.io/library/platform-demo
    tag: bf4b617        # Kargo bumps
  scaledObject:
    http:
      hosts:
        - platform-demo-dev.10.0.0.200.nip.io
        - dev.demo.devandre.sbs
  certificate:
    dnsNames:
      - platform-demo-dev.10.0.0.200.nip.io
ssoIngress:
  hosts:
    - platform-demo-dev.10.0.0.200.nip.io
    - dev.demo.devandre.sbs
appConfig:
  APP_ENV: development
  LOG_LEVEL: debug
