apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform-demo-staging
resources:
  - ../../base
  - scaledobject.yaml
# Tag promoted manually: after dev is validated, open a PR bumping newTag here.
images:
  - name: harbor.10.0.0.200.nip.io/library/platform-demo
    newTag: "0b7cb75"
patches:
  - path: patch-resources.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Rollout
      name: platform-demo
