apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-demo
spec:
  replicas: 2
  template:
    spec:
      containers:
        - name: platform-demo
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
