apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-ui-tls
  namespace: kube-system
spec:
  secretName: hubble-ui-tls
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: minicloud-ca
    kind: ClusterIssuer
  dnsNames:
    - hubble.10.0.0.200.nip.io
