---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: minicloud-plane-dev
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: "256Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
    pods: "10"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limits
  namespace: minicloud-plane-dev
spec:
  limits:
    - type: Container
      default:
        cpu: "100m"
        memory: "128Mi"
      defaultRequest:
        cpu: "10m"
        memory: "32Mi"
      max:
        cpu: "500m"
        memory: "512Mi"
