apiVersion: v1
kind: Service
metadata:
  name: ktayl-ldap-outpost
  namespace: authentik
  labels: { app: ktayl-ldap-outpost }
spec:
  selector: { app: ktayl-ldap-outpost }
  ports:
    - { name: ldap, port: 3389, targetPort: 3389 }
    - { name: ldaps, port: 6636, targetPort: 6636 }
