apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minicloud-plane-dev
resources:
- ../../base
images:
- name: harbor.10.0.0.200.nip.io/library/minicloud-plane
  newTag: dev-acaa05d
