---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: platform-demo
  namespace: gitops-demo
  annotations:
    nginx.org/redirect-to-https: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - platform-demo.10.0.0.200.nip.io
      secretName: platform-demo-tls
  rules:
    - host: platform-demo.10.0.0.200.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: platform-demo
                port:
                  name: http
