---
apiVersion: v1
kind: Namespace
metadata:
  name: vaultwarden
  labels:
    kubernetes.io/metadata.name: vaultwarden
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/warn-version: latest
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: vaultwarden
automountServiceAccountToken: false
