apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: SERVICE_NAME-dev
resources:
  - ../../base
# CI updates newTag on every push to main.
images:
  - name: harbor.10.0.0.200.nip.io/library/SERVICE_NAME
    newTag: "latest"
patches:
  - path: patch-resources.yaml
