---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nextcloud-tls
  namespace: nextcloud
spec:
  secretName: nextcloud-tls
  duration: 2160h
  renewBefore: 720h
  issuerRef:
    kind: ClusterIssuer
    name: minicloud-ca
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - cloud.10.0.0.200.nip.io
    - cloud.devandre.sbs
