apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: open-webui-metrics
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    release: kps
spec:
  namespaceSelector:
    matchNames:
      - ai
  selector:
    matchLabels:
      app.kubernetes.io/name: open-webui
      app.kubernetes.io/component: open-webui
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
