---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: minicloud-ca
spec:
  vault:
    server: https://vault.10.0.0.200.nip.io
    path: pki/sign/cert-manager
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUNBekNDQWFpZ0F3SUJBZ0lVWFM4bFpnOGs5eWg0Mkd5ZDdFQkRlUXB2cm5Bd0NnWUlLb1pJemowRUF3SXcKWHpFYk1Ca0dBMVVFQ2hNU1lXNWtjbVZzWVdseUxYQnNZWFJtYjNKdE1Sc3dHUVlEVlFRTEV4SnRhVzVwWTJ4dgpkV1FnY0d4aGRHWnZjbTB4SXpBaEJnTlZCQU1UR20xcGJtbGpiRzkxWkNCSmJuUmxjbTVoYkNCU2IyOTBJRU5CCk1CNFhEVEkyTURVd09URXhOVFkwTmxvWERUTTJNRFV3TmpFeE5UWTBObG93WHpFYk1Ca0dBMVVFQ2hNU1lXNWsKY21Wc1lXbHlMWEJzWVhSbWIzSnRNUnN3R1FZRFZRUUxFeEp0YVc1cFkyeHZkV1FnY0d4aGRHWnZjbTB4SXpBaApCZ05WQkFNVEdtMXBibWxqYkc5MVpDQkpiblJsY201aGJDQlNiMjkwSUVOQk1Ga3dFd1lIS29aSXpqMENBUVlJCktvWkl6ajBEQVFjRFFnQUVJWVNJYjlzYXpPMU1PL0RFOFRGSXBRWW5sUG1oK21WcGU3cCtsQmw3Z291U2VmZC8KU1VBSmQwdDd4Tk1xV3FtZ255YU1paXcwVG9oSEEzc2gxWWNITktOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdLawpNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGQUNsMnZCeGhnUlgwUHZxR2FwY2swc000ZWZkCk1Bb0dDQ3FHU000OUJBTUNBMGtBTUVZQ0lRQ0FweUh6QVJxVjNSbHpGUjV1SWRwd3l5VXlHSnVnTTg5Tlh2V3YKYkVKN2dRSWhBSnE1bW5aS1MvRUpUTVBZemt1cTMzSzRnK0ZKcDJ6dCtWcFVrZzI0RVRLTwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    auth:
      kubernetes:
        mountPath: /v1/auth/kubernetes
        role: cert-manager
        serviceAccountRef:
          name: cert-manager
