apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: synapse-secrets
  namespace: chat
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: synapse-secrets
    creationPolicy: Owner
  data:
    - secretKey: oidc-client-id
      remoteRef:
        key: platform/matrix
        property: oidc-client-id
    - secretKey: oidc-client-secret
      remoteRef:
        key: platform/matrix
        property: oidc-client-secret
    - secretKey: registration-shared-secret
      remoteRef:
        key: platform/matrix
        property: registration-shared-secret
    - secretKey: macaroon-secret-key
      remoteRef:
        key: platform/matrix
        property: macaroon-secret-key
    - secretKey: pg-password
      remoteRef:
        key: platform/matrix
        property: pg-password
