apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: postgresql-synapse-secret
  namespace: chat
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgresql-synapse-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: platform/postgresql-synapse
        property: postgres-password
    - secretKey: pg-password
      remoteRef:
        key: platform/postgresql-synapse
        property: pg-password
