apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: prometheus-tls
  namespace: monitoring
spec:
  secretName: prometheus-tls
  duration: 2160h
  renewBefore: 720h
  issuerRef:
    kind: ClusterIssuer
    name: minicloud-ca
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - prometheus.10.0.0.200.nip.io
