apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backstage-postgres-secret
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: backstage-postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: platform/backstage-postgres
        property: password
