---
apiVersion: v1
kind: Namespace
metadata:
  name: retrieva
  labels:
    kubernetes.io/metadata.name: retrieva
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: retrieva-quota
  namespace: retrieva
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 5Gi
    count/pods: "12"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: retrieva-limits
  namespace: retrieva
spec:
  limits:
    - type: Container
      default:
        cpu: 300m
        memory: 384Mi
      defaultRequest:
        cpu: 50m
        memory: 128Mi
