apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stalwart-secret
  namespace: mail
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: stalwart-secret
    creationPolicy: Owner
  data:
    - secretKey: STALWART_ADMIN_SECRET
      remoteRef:
        key: secret/platform/mail
        property: stalwart-admin-secret
    - secretKey: SMTP_RELAY_HOST
      remoteRef:
        key: secret/platform/mail
        property: smtp-relay-host
    - secretKey: SMTP_RELAY_PORT
      remoteRef:
        key: secret/platform/mail
        property: smtp-relay-port
    - secretKey: SMTP_RELAY_USER
      remoteRef:
        key: secret/platform/mail
        property: smtp-relay-user
    - secretKey: SMTP_RELAY_PASSWORD
      remoteRef:
        key: secret/platform/mail
        property: smtp-relay-password
