apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-stable-secrets
  namespace: harbor
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: vault-backend
  target:
    name: harbor-stable-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: JOBSERVICE_SECRET
      remoteRef:
        key: platform/harbor
        property: jobservice-secret
    - secretKey: secret
      remoteRef:
        key: platform/harbor
        property: core-secret
