apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jitsi-tls
  namespace: collab
spec:
  secretName: jitsi-tls
  duration: 2160h
  renewBefore: 720h
  issuerRef:
    kind: ClusterIssuer
    name: minicloud-ca
    group: cert-manager.io
  privateKey:
    algorithm: ECDSA
    size: 256
  dnsNames:
    - meet.devandre.sbs
    - meet.10.0.0.200.nip.io
