apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-demo-tls
spec:
  secretName: platform-demo-tls
  issuerRef:
    name: minicloud-ca
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - platform-demo.10.0.0.200.nip.io
  duration: 2160h
  renewBefore: 720h
  privateKey:
    algorithm: ECDSA
    size: 256
