apiVersion: v1
kind: Service
metadata:
  name: ktayl-policy-service
  labels:
    app: ktayl-policy-service
spec:
  selector:
    app: ktayl-policy-service
  ports:
    - name: http
      port: 80
      targetPort: http
