apiVersion: v1
kind: ResourceQuota
metadata:
  name: staging-quota
  namespace: insurance-staging
spec:
  hard:
    requests.cpu: "1"
    requests.memory: "2Gi"
    limits.cpu: "4"
    limits.memory: "8Gi"
    pods: "20"
    persistentvolumeclaims: "10"
    requests.storage: "50Gi"
