apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minicloud-plane-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  source:
    repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
    targetRevision: main
    path: services/minicloud-plane/minicloud-1/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: minicloud-plane-staging
  ignoreDifferences:
    - group: argoproj.io
      kind: Rollout
      jsonPointers:
        - /spec/replicas
        - /spec/template/metadata/annotations
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
