apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: backend-prod
  namespace: ktayl-iam-kargo
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: ktayl-iam-backend
      sources:
        stages: [backend-dev]
  promotionTemplate:
    spec:
      vars:
        - name: gitopsRepo
          value: https://github.com/andrelair-platform/minicloud-gitops.git
        - name: img
          value: ghcr.io/andrelair-platform/ktayl-iam-backend
      steps:
        - uses: git-clone
          as: clone
          config:
            repoURL: ${{ vars.gitopsRepo }}
            checkout:
              - branch: main
                path: ./repo
        - uses: yaml-update
          as: set-image
          config:
            path: ./repo/services/ktayl-iam/helm/values-prod.yaml
            updates:
              - key: backend.image.tag
                value: '${{ quote(imageFrom(vars.img).Tag) }}'
        - uses: git-commit
          as: commit
          config:
            path: ./repo
            message: 'kargo(ktayl-iam): promote backend ${{ imageFrom(vars.img).Tag }} to PROD'
        - uses: git-push
          as: push
          if: ${{ outputs.commit.commit != outputs.clone.commits['./repo'] }}
          config:
            path: ./repo
            generateTargetBranch: true
        - uses: git-open-pr
          as: open-pr
          if: ${{ outputs.commit.commit != outputs.clone.commits['./repo'] }}
          config:
            repoURL: ${{ vars.gitopsRepo }}
            sourceBranch: ${{ outputs.push.branch }}
            targetBranch: main
            provider: github
            title: 'kargo(ktayl-iam): promote backend ${{ imageFrom(vars.img).Tag }} to PROD'
            labels: [kargo, env-prod]
        - uses: git-wait-for-pr
          as: wait-pr
          if: ${{ outputs.commit.commit != outputs.clone.commits['./repo'] }}
          config:
            repoURL: ${{ vars.gitopsRepo }}
            prNumber: ${{ outputs['open-pr'].pr.id }}
