apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kargo-git-credentials
  namespace: retrieva-kargo
spec:
  refreshInterval: 1h
  secretStoreRef: { name: vault-backend, kind: ClusterSecretStore }
  target:
    name: kargo-git-credentials
    creationPolicy: Owner
    template:
      metadata: { labels: { kargo.akuity.io/cred-type: git } }
      data:
        repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
        username: "{{ .username }}"
        password: "{{ .token }}"
  data:
    - secretKey: username
      remoteRef: { key: platform/kargo, property: git-username }
    - secretKey: token
      remoteRef: { key: platform/kargo, property: git-token }
