apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: retrieva
  namespace: retrieva-kargo
spec:
  interval: 5m
  freightCreationPolicy: Automatic
  subscriptions:
    - image:
        repoURL: ghcr.io/andrelair-platform/retrieva-backend
        imageSelectionStrategy: NewestBuild
        allowTagsRegexes:
          - ^[0-9a-f]{7,40}$
        discoveryLimit: 5
    - image:
        repoURL: ghcr.io/andrelair-platform/retrieva-frontend
        imageSelectionStrategy: NewestBuild
        allowTagsRegexes:
          - ^[0-9a-f]{7,40}$
        discoveryLimit: 5
