---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: "9.5.13"
      helm:
        releaseName: argo-cd
        valueFiles:
          - $values/helm-values/argocd-values.yaml
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
    - group: ""
      kind: ConfigMap
      name: argocd-cm
      namespace: argocd
      jqPathExpressions:
        - '.data["oidc.config"]'
        - '.data["url"]'
    - group: ""
      kind: Secret
      name: argocd-secret
      namespace: argocd
      jsonPointers:
        - /data
        - /metadata/annotations
    - group: apps
      kind: Deployment
      jqPathExpressions:
        - '.spec.template.metadata.annotations'
    - group: apps
      kind: StatefulSet
      jqPathExpressions:
        - '.spec.template.metadata.annotations'
