apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  source:
    repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
    targetRevision: main
    path: manifests/event-demo
    verifySignature: true
  destination:
    server: https://kubernetes.default.svc
    namespace: event-demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
