---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.18.3"
      helm:
        releaseName: harbor
        valueFiles:
          - $values/helm-values/harbor-values.yaml
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      path: manifests/harbor
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - kind: Secret
      name: harbor-core
      namespace: harbor
      jsonPointers:
        - /data/HARBOR_ADMIN_PASSWORD
        - /data/tls.crt
        - /data/tls.key
        - /data/secret
        - /data/secretKey
        - /data/CSRF_KEY
    - group: apps
      kind: Deployment
      namespace: harbor
      jsonPointers:
        - /spec/template/metadata/annotations/checksum~1secret
        - /spec/template/metadata/annotations/checksum~1secret-core
        - /spec/template/metadata/annotations/checksum~1secret-jobservice
        - /spec/template/metadata/annotations/checksum~1configmap
        - /spec/template/metadata/annotations/checksum~1configmap-env
    - kind: PersistentVolumeClaim
      jsonPointers:
        - /spec/volumeName
        - /spec/volumeMode
