---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langfuse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  sources:
    - repoURL: https://langfuse.github.io/langfuse-k8s
      chart: langfuse
      targetRevision: "1.5.37"
      helm:
        releaseName: langfuse
        valueFiles:
          - $values/helm-values/langfuse-values.yaml
    - repoURL: https://github.com/andrelair-platform/minicloud-ansible.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: langfuse
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
