---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix-synapse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  sources:
    - repoURL: https://ananace.gitlab.io/charts
      chart: matrix-synapse
      targetRevision: 3.12.31
      helm:
        valueFiles:
          - $values/helm-values/synapse-values.yaml
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      path: manifests/matrix
  destination:
    server: https://kubernetes.default.svc
    namespace: chat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
