---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  sources:
    - repoURL: https://nextcloud.github.io/helm/
      chart: nextcloud
      targetRevision: 9.1.3
      helm:
        valueFiles:
          - $values/helm-values/nextcloud-values.yaml
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      path: manifests/nextcloud
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
