---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ollama-secondary
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  sources:
    - repoURL: https://otwld.github.io/ollama-helm/
      chart: ollama
      targetRevision: "1.61.0"
      helm:
        releaseName: ollama-secondary
        valueFiles:
          - $values/helm-values/ollama-secondary-values.yaml
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ai
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
