---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: plane-ce
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  sources:
    - repoURL: https://helm.plane.so/
      chart: plane-ce
      targetRevision: "1.6.0"
      helm:
        releaseName: plane-ce
        valueFiles:
          - $values/helm-values/plane-values.yaml
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      path: manifests/plane
  destination:
    server: https://kubernetes.default.svc
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
    - group: batch
      kind: Job
      jsonPointers:
        - /spec/template/metadata
