apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: tempo
      targetRevision: "1.24.4"
      helm:
        releaseName: tempo
        valueFiles:
          - $values/helm-values/tempo-values.yaml
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      path: manifests/tempo
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
