---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vpa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: minicloud-platform
  sources:
    - repoURL: https://charts.fairwinds.com/stable
      chart: vpa
      targetRevision: "4.12.3"
      helm:
        valueFiles:
          - $values/helm-values/vpa-values.yaml
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      ref: values
    - repoURL: https://github.com/andrelair-platform/minicloud-gitops.git
      targetRevision: main
      path: manifests/vpa
  destination:
    server: https://kubernetes.default.svc
    namespace: vpa-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
