cainjector:
  resources:
    limits:
      cpu: 100m
      memory: 256Mi
    requests:
      cpu: 25m
      memory: 128Mi
crds:
  enabled: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
    labels:
      release: kube-prometheus-stack
replicaCount: 1
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 25m
    memory: 64Mi
webhook:
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 25m
      memory: 64Mi
