apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: platform-demo
  namespace: platform-demo
spec:
  interval: 5m
  freightCreationPolicy: Automatic
  subscriptions:
    - image:
        repoURL: ghcr.io/andrelair-platform/platform-demo
        imageSelectionStrategy: NewestBuild
        allowTagsRegexes:
          - ^[0-9a-f]{7,40}$
        discoveryLimit: 5
